# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dialog-journal',
                'doc_host': 'https://lisa.github.io',
                'git_url': 'https://github.com/lisa/dialog-journal',
                'lib_path': 'dialog_journal'},
  'syms': {'dialog_journal.core': {'dialog_journal.core.foo': ('core.html#foo', 'dialog_journal/core.py')}}}
